spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database?currentSchema=axon-orders
    username: my_username
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id.db_structure_naming_strategy: legacy

server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing